// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: auth/auth_service.proto

package authconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
	auth "yourapp/pb/auth"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "yourapp.auth.AuthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthServiceLoginProcedure is the fully-qualified name of the AuthService's Login RPC.
	AuthServiceLoginProcedure = "/yourapp.auth.AuthService/Login"
	// AuthServiceRegisterProcedure is the fully-qualified name of the AuthService's Register RPC.
	AuthServiceRegisterProcedure = "/yourapp.auth.AuthService/Register"
)

// AuthServiceClient is a client for the yourapp.auth.AuthService service.
type AuthServiceClient interface {
	Login(context.Context, *connect.Request[auth.LoginRequest]) (*connect.Response[auth.AuthResponse], error)
	Register(context.Context, *connect.Request[auth.RegisterRequest]) (*connect.Response[auth.AuthResponse], error)
}

// NewAuthServiceClient constructs a client for the yourapp.auth.AuthService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authServiceMethods := auth.File_auth_auth_service_proto.Services().ByName("AuthService").Methods()
	return &authServiceClient{
		login: connect.NewClient[auth.LoginRequest, auth.AuthResponse](
			httpClient,
			baseURL+AuthServiceLoginProcedure,
			connect.WithSchema(authServiceMethods.ByName("Login")),
			connect.WithClientOptions(opts...),
		),
		register: connect.NewClient[auth.RegisterRequest, auth.AuthResponse](
			httpClient,
			baseURL+AuthServiceRegisterProcedure,
			connect.WithSchema(authServiceMethods.ByName("Register")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	login    *connect.Client[auth.LoginRequest, auth.AuthResponse]
	register *connect.Client[auth.RegisterRequest, auth.AuthResponse]
}

// Login calls yourapp.auth.AuthService.Login.
func (c *authServiceClient) Login(ctx context.Context, req *connect.Request[auth.LoginRequest]) (*connect.Response[auth.AuthResponse], error) {
	return c.login.CallUnary(ctx, req)
}

// Register calls yourapp.auth.AuthService.Register.
func (c *authServiceClient) Register(ctx context.Context, req *connect.Request[auth.RegisterRequest]) (*connect.Response[auth.AuthResponse], error) {
	return c.register.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the yourapp.auth.AuthService service.
type AuthServiceHandler interface {
	Login(context.Context, *connect.Request[auth.LoginRequest]) (*connect.Response[auth.AuthResponse], error)
	Register(context.Context, *connect.Request[auth.RegisterRequest]) (*connect.Response[auth.AuthResponse], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authServiceMethods := auth.File_auth_auth_service_proto.Services().ByName("AuthService").Methods()
	authServiceLoginHandler := connect.NewUnaryHandler(
		AuthServiceLoginProcedure,
		svc.Login,
		connect.WithSchema(authServiceMethods.ByName("Login")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceRegisterHandler := connect.NewUnaryHandler(
		AuthServiceRegisterProcedure,
		svc.Register,
		connect.WithSchema(authServiceMethods.ByName("Register")),
		connect.WithHandlerOptions(opts...),
	)
	return "/yourapp.auth.AuthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthServiceLoginProcedure:
			authServiceLoginHandler.ServeHTTP(w, r)
		case AuthServiceRegisterProcedure:
			authServiceRegisterHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) Login(context.Context, *connect.Request[auth.LoginRequest]) (*connect.Response[auth.AuthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("yourapp.auth.AuthService.Login is not implemented"))
}

func (UnimplementedAuthServiceHandler) Register(context.Context, *connect.Request[auth.RegisterRequest]) (*connect.Response[auth.AuthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("yourapp.auth.AuthService.Register is not implemented"))
}
