// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: admin/user_service.proto

package adminconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
	admin "yourapp/pb/admin"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// UserServiceName is the fully-qualified name of the UserService service.
	UserServiceName = "yourapp.admin.UserService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UserServiceCreateUserProcedure is the fully-qualified name of the UserService's CreateUser RPC.
	UserServiceCreateUserProcedure = "/yourapp.admin.UserService/CreateUser"
	// UserServiceGetUserProcedure is the fully-qualified name of the UserService's GetUser RPC.
	UserServiceGetUserProcedure = "/yourapp.admin.UserService/GetUser"
	// UserServiceUpdateUserProcedure is the fully-qualified name of the UserService's UpdateUser RPC.
	UserServiceUpdateUserProcedure = "/yourapp.admin.UserService/UpdateUser"
	// UserServiceDeleteUserProcedure is the fully-qualified name of the UserService's DeleteUser RPC.
	UserServiceDeleteUserProcedure = "/yourapp.admin.UserService/DeleteUser"
	// UserServiceListUsersProcedure is the fully-qualified name of the UserService's ListUsers RPC.
	UserServiceListUsersProcedure = "/yourapp.admin.UserService/ListUsers"
)

// UserServiceClient is a client for the yourapp.admin.UserService service.
type UserServiceClient interface {
	CreateUser(context.Context, *connect.Request[admin.CreateUserRequest]) (*connect.Response[admin.UserResponse], error)
	GetUser(context.Context, *connect.Request[admin.GetUserRequest]) (*connect.Response[admin.UserResponse], error)
	UpdateUser(context.Context, *connect.Request[admin.UpdateUserRequest]) (*connect.Response[admin.UserResponse], error)
	DeleteUser(context.Context, *connect.Request[admin.DeleteUserRequest]) (*connect.Response[admin.DeleteUserResponse], error)
	ListUsers(context.Context, *connect.Request[admin.ListUsersRequest]) (*connect.Response[admin.ListUsersResponse], error)
}

// NewUserServiceClient constructs a client for the yourapp.admin.UserService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUserServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UserServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	userServiceMethods := admin.File_admin_user_service_proto.Services().ByName("UserService").Methods()
	return &userServiceClient{
		createUser: connect.NewClient[admin.CreateUserRequest, admin.UserResponse](
			httpClient,
			baseURL+UserServiceCreateUserProcedure,
			connect.WithSchema(userServiceMethods.ByName("CreateUser")),
			connect.WithClientOptions(opts...),
		),
		getUser: connect.NewClient[admin.GetUserRequest, admin.UserResponse](
			httpClient,
			baseURL+UserServiceGetUserProcedure,
			connect.WithSchema(userServiceMethods.ByName("GetUser")),
			connect.WithClientOptions(opts...),
		),
		updateUser: connect.NewClient[admin.UpdateUserRequest, admin.UserResponse](
			httpClient,
			baseURL+UserServiceUpdateUserProcedure,
			connect.WithSchema(userServiceMethods.ByName("UpdateUser")),
			connect.WithClientOptions(opts...),
		),
		deleteUser: connect.NewClient[admin.DeleteUserRequest, admin.DeleteUserResponse](
			httpClient,
			baseURL+UserServiceDeleteUserProcedure,
			connect.WithSchema(userServiceMethods.ByName("DeleteUser")),
			connect.WithClientOptions(opts...),
		),
		listUsers: connect.NewClient[admin.ListUsersRequest, admin.ListUsersResponse](
			httpClient,
			baseURL+UserServiceListUsersProcedure,
			connect.WithSchema(userServiceMethods.ByName("ListUsers")),
			connect.WithClientOptions(opts...),
		),
	}
}

// userServiceClient implements UserServiceClient.
type userServiceClient struct {
	createUser *connect.Client[admin.CreateUserRequest, admin.UserResponse]
	getUser    *connect.Client[admin.GetUserRequest, admin.UserResponse]
	updateUser *connect.Client[admin.UpdateUserRequest, admin.UserResponse]
	deleteUser *connect.Client[admin.DeleteUserRequest, admin.DeleteUserResponse]
	listUsers  *connect.Client[admin.ListUsersRequest, admin.ListUsersResponse]
}

// CreateUser calls yourapp.admin.UserService.CreateUser.
func (c *userServiceClient) CreateUser(ctx context.Context, req *connect.Request[admin.CreateUserRequest]) (*connect.Response[admin.UserResponse], error) {
	return c.createUser.CallUnary(ctx, req)
}

// GetUser calls yourapp.admin.UserService.GetUser.
func (c *userServiceClient) GetUser(ctx context.Context, req *connect.Request[admin.GetUserRequest]) (*connect.Response[admin.UserResponse], error) {
	return c.getUser.CallUnary(ctx, req)
}

// UpdateUser calls yourapp.admin.UserService.UpdateUser.
func (c *userServiceClient) UpdateUser(ctx context.Context, req *connect.Request[admin.UpdateUserRequest]) (*connect.Response[admin.UserResponse], error) {
	return c.updateUser.CallUnary(ctx, req)
}

// DeleteUser calls yourapp.admin.UserService.DeleteUser.
func (c *userServiceClient) DeleteUser(ctx context.Context, req *connect.Request[admin.DeleteUserRequest]) (*connect.Response[admin.DeleteUserResponse], error) {
	return c.deleteUser.CallUnary(ctx, req)
}

// ListUsers calls yourapp.admin.UserService.ListUsers.
func (c *userServiceClient) ListUsers(ctx context.Context, req *connect.Request[admin.ListUsersRequest]) (*connect.Response[admin.ListUsersResponse], error) {
	return c.listUsers.CallUnary(ctx, req)
}

// UserServiceHandler is an implementation of the yourapp.admin.UserService service.
type UserServiceHandler interface {
	CreateUser(context.Context, *connect.Request[admin.CreateUserRequest]) (*connect.Response[admin.UserResponse], error)
	GetUser(context.Context, *connect.Request[admin.GetUserRequest]) (*connect.Response[admin.UserResponse], error)
	UpdateUser(context.Context, *connect.Request[admin.UpdateUserRequest]) (*connect.Response[admin.UserResponse], error)
	DeleteUser(context.Context, *connect.Request[admin.DeleteUserRequest]) (*connect.Response[admin.DeleteUserResponse], error)
	ListUsers(context.Context, *connect.Request[admin.ListUsersRequest]) (*connect.Response[admin.ListUsersResponse], error)
}

// NewUserServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUserServiceHandler(svc UserServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	userServiceMethods := admin.File_admin_user_service_proto.Services().ByName("UserService").Methods()
	userServiceCreateUserHandler := connect.NewUnaryHandler(
		UserServiceCreateUserProcedure,
		svc.CreateUser,
		connect.WithSchema(userServiceMethods.ByName("CreateUser")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceGetUserHandler := connect.NewUnaryHandler(
		UserServiceGetUserProcedure,
		svc.GetUser,
		connect.WithSchema(userServiceMethods.ByName("GetUser")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceUpdateUserHandler := connect.NewUnaryHandler(
		UserServiceUpdateUserProcedure,
		svc.UpdateUser,
		connect.WithSchema(userServiceMethods.ByName("UpdateUser")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceDeleteUserHandler := connect.NewUnaryHandler(
		UserServiceDeleteUserProcedure,
		svc.DeleteUser,
		connect.WithSchema(userServiceMethods.ByName("DeleteUser")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceListUsersHandler := connect.NewUnaryHandler(
		UserServiceListUsersProcedure,
		svc.ListUsers,
		connect.WithSchema(userServiceMethods.ByName("ListUsers")),
		connect.WithHandlerOptions(opts...),
	)
	return "/yourapp.admin.UserService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UserServiceCreateUserProcedure:
			userServiceCreateUserHandler.ServeHTTP(w, r)
		case UserServiceGetUserProcedure:
			userServiceGetUserHandler.ServeHTTP(w, r)
		case UserServiceUpdateUserProcedure:
			userServiceUpdateUserHandler.ServeHTTP(w, r)
		case UserServiceDeleteUserProcedure:
			userServiceDeleteUserHandler.ServeHTTP(w, r)
		case UserServiceListUsersProcedure:
			userServiceListUsersHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUserServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedUserServiceHandler struct{}

func (UnimplementedUserServiceHandler) CreateUser(context.Context, *connect.Request[admin.CreateUserRequest]) (*connect.Response[admin.UserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("yourapp.admin.UserService.CreateUser is not implemented"))
}

func (UnimplementedUserServiceHandler) GetUser(context.Context, *connect.Request[admin.GetUserRequest]) (*connect.Response[admin.UserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("yourapp.admin.UserService.GetUser is not implemented"))
}

func (UnimplementedUserServiceHandler) UpdateUser(context.Context, *connect.Request[admin.UpdateUserRequest]) (*connect.Response[admin.UserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("yourapp.admin.UserService.UpdateUser is not implemented"))
}

func (UnimplementedUserServiceHandler) DeleteUser(context.Context, *connect.Request[admin.DeleteUserRequest]) (*connect.Response[admin.DeleteUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("yourapp.admin.UserService.DeleteUser is not implemented"))
}

func (UnimplementedUserServiceHandler) ListUsers(context.Context, *connect.Request[admin.ListUsersRequest]) (*connect.Response[admin.ListUsersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("yourapp.admin.UserService.ListUsers is not implemented"))
}
