// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: i18n/i18n.proto

package i18n

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	I18NService_GetTranslations_FullMethodName = "/yourapp.i18n.I18nService/GetTranslations"
)

// I18NServiceClient is the client API for I18NService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// I18n service provides internationalization functionality
type I18NServiceClient interface {
	// GetTranslations returns all translations for a specific language
	GetTranslations(ctx context.Context, in *GetTranslationsRequest, opts ...grpc.CallOption) (*GetTranslationsResponse, error)
}

type i18NServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewI18NServiceClient(cc grpc.ClientConnInterface) I18NServiceClient {
	return &i18NServiceClient{cc}
}

func (c *i18NServiceClient) GetTranslations(ctx context.Context, in *GetTranslationsRequest, opts ...grpc.CallOption) (*GetTranslationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTranslationsResponse)
	err := c.cc.Invoke(ctx, I18NService_GetTranslations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// I18NServiceServer is the server API for I18NService service.
// All implementations must embed UnimplementedI18NServiceServer
// for forward compatibility.
//
// I18n service provides internationalization functionality
type I18NServiceServer interface {
	// GetTranslations returns all translations for a specific language
	GetTranslations(context.Context, *GetTranslationsRequest) (*GetTranslationsResponse, error)
	mustEmbedUnimplementedI18NServiceServer()
}

// UnimplementedI18NServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedI18NServiceServer struct{}

func (UnimplementedI18NServiceServer) GetTranslations(context.Context, *GetTranslationsRequest) (*GetTranslationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTranslations not implemented")
}
func (UnimplementedI18NServiceServer) mustEmbedUnimplementedI18NServiceServer() {}
func (UnimplementedI18NServiceServer) testEmbeddedByValue()                     {}

// UnsafeI18NServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to I18NServiceServer will
// result in compilation errors.
type UnsafeI18NServiceServer interface {
	mustEmbedUnimplementedI18NServiceServer()
}

func RegisterI18NServiceServer(s grpc.ServiceRegistrar, srv I18NServiceServer) {
	// If the following call pancis, it indicates UnimplementedI18NServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&I18NService_ServiceDesc, srv)
}

func _I18NService_GetTranslations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTranslationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(I18NServiceServer).GetTranslations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: I18NService_GetTranslations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(I18NServiceServer).GetTranslations(ctx, req.(*GetTranslationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// I18NService_ServiceDesc is the grpc.ServiceDesc for I18NService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var I18NService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "yourapp.i18n.I18nService",
	HandlerType: (*I18NServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTranslations",
			Handler:    _I18NService_GetTranslations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "i18n/i18n.proto",
}
