// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.1
// source: i18n/i18n.proto

package i18n

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetTranslationsRequest represents a request to get translations
type GetTranslationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// language is the language code (e.g., "en", "vi")
	Language      string `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTranslationsRequest) Reset() {
	*x = GetTranslationsRequest{}
	mi := &file_i18n_i18n_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTranslationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTranslationsRequest) ProtoMessage() {}

func (x *GetTranslationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_i18n_i18n_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTranslationsRequest.ProtoReflect.Descriptor instead.
func (*GetTranslationsRequest) Descriptor() ([]byte, []int) {
	return file_i18n_i18n_proto_rawDescGZIP(), []int{0}
}

func (x *GetTranslationsRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

// GetTranslationsResponse represents a response containing translations
type GetTranslationsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// translations is a JSON-encoded map of translation keys to their values
	Translations  []byte `protobuf:"bytes,1,opt,name=translations,proto3" json:"translations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTranslationsResponse) Reset() {
	*x = GetTranslationsResponse{}
	mi := &file_i18n_i18n_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTranslationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTranslationsResponse) ProtoMessage() {}

func (x *GetTranslationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_i18n_i18n_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTranslationsResponse.ProtoReflect.Descriptor instead.
func (*GetTranslationsResponse) Descriptor() ([]byte, []int) {
	return file_i18n_i18n_proto_rawDescGZIP(), []int{1}
}

func (x *GetTranslationsResponse) GetTranslations() []byte {
	if x != nil {
		return x.Translations
	}
	return nil
}

var File_i18n_i18n_proto protoreflect.FileDescriptor

const file_i18n_i18n_proto_rawDesc = "" +
	"\n" +
	"\x0fi18n/i18n.proto\x12\fyourapp.i18n\x1a\x1cgoogle/api/annotations.proto\x1a\"envoyproxy/validate/validate.proto\"K\n" +
	"\x16GetTranslationsRequest\x121\n" +
	"\blanguage\x18\x01 \x01(\tB\x15\xfaB\x12r\x10\x10\x02\x18\x022\n" +
	"^[a-z]{2}$R\blanguage\"=\n" +
	"\x17GetTranslationsResponse\x12\"\n" +
	"\ftranslations\x18\x01 \x01(\fR\ftranslations2\x87\x01\n" +
	"\vI18nService\x12x\n" +
	"\x0fGetTranslations\x12$.yourapp.i18n.GetTranslationsRequest\x1a%.yourapp.i18n.GetTranslationsResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/lang/{language}B\x16Z\x14yourapp/pb/i18n;i18nb\x06proto3"

var (
	file_i18n_i18n_proto_rawDescOnce sync.Once
	file_i18n_i18n_proto_rawDescData []byte
)

func file_i18n_i18n_proto_rawDescGZIP() []byte {
	file_i18n_i18n_proto_rawDescOnce.Do(func() {
		file_i18n_i18n_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_i18n_i18n_proto_rawDesc), len(file_i18n_i18n_proto_rawDesc)))
	})
	return file_i18n_i18n_proto_rawDescData
}

var file_i18n_i18n_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_i18n_i18n_proto_goTypes = []any{
	(*GetTranslationsRequest)(nil),  // 0: yourapp.i18n.GetTranslationsRequest
	(*GetTranslationsResponse)(nil), // 1: yourapp.i18n.GetTranslationsResponse
}
var file_i18n_i18n_proto_depIdxs = []int32{
	0, // 0: yourapp.i18n.I18nService.GetTranslations:input_type -> yourapp.i18n.GetTranslationsRequest
	1, // 1: yourapp.i18n.I18nService.GetTranslations:output_type -> yourapp.i18n.GetTranslationsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_i18n_i18n_proto_init() }
func file_i18n_i18n_proto_init() {
	if File_i18n_i18n_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_i18n_i18n_proto_rawDesc), len(file_i18n_i18n_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_i18n_i18n_proto_goTypes,
		DependencyIndexes: file_i18n_i18n_proto_depIdxs,
		MessageInfos:      file_i18n_i18n_proto_msgTypes,
	}.Build()
	File_i18n_i18n_proto = out.File
	file_i18n_i18n_proto_goTypes = nil
	file_i18n_i18n_proto_depIdxs = nil
}
